<a href="https://colab.research.google.com/github/ithelga/beeline-banner-ab-test/blob/dev/notebooks/Team1_HW2_Data_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **SmartAds Efficiency**: Оптимизация эффективности маркетинговых каналов

## [STAGE 1] **Предобработка данных**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler
import warnings
warnings.filterwarnings('ignore')

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

colors = ["#FFAFCC", "#FFC8DD", "#CDB4DB", "#BDE0FE", "#A2D2FF"] # СТАРЫЕ ЦВЕТА!!!!!!!!!!!!!!!!!!!!!!

graph_path = 'drive/MyDrive/Colab Notebooks/Beeline Banner AB-test/graph'
data_path = 'drive/MyDrive/Colab Notebooks/Beeline Banner AB-test/data'

Mounted at /content/drive

### Загрузка датасетов Google Disk

In [ ]:
CD_banner_df = pd.read_csv(f'{data_path}/CD_banner.csv', sep=";")
CD_banner_df.head(2)

,banner_id,creative_type (статика/видео/анимация),message (сообщение на баннере),size,target_audience_segment
0,1,video,Сервис,300x250,value
1,2,rich,Новинка,300x250,youth

In [ ]:
CD_campaign_df = pd.read_csv(f'{data_path}/CD_campaign.csv', sep=";")
CD_campaign_df.head(2)

   campaign_id  daily_budget  start_date    end_date
0            1     175071.43  01.02.2025  17.03.2025
1            2      95601.86  01.02.2025  17.03.2025

In [ ]:
CD_user_df = pd.read_csv(f'{data_path}/CD_user.csv', sep=";")
CD_user_df.head(2)

   User_id  segment   tariff date_create    date_end
0        1  premium  premium  2025-01-18  2025-02-25
1        2   family    basic  2024-12-18  2025-01-20

In [ ]:
Fct_actions_df = pd.read_csv(f'{data_path}/Fct_actions.csv', sep=";")
Fct_actions_df.head(2)

   user_id        session_start actions (регистрация, первый заказ и т.д.)
0     2908  2025-02-02 12:49:24                               registration
1     2908  2025-02-03 10:11:53                                first_order

In [ ]:
Fct_banners_show_df = pd.read_csv(f'{data_path}/Fct_banners_show.csv', sep=";")
Fct_banners_show_df.head(2)

,banner_id,campaign_id,user_id,timestamp,placement (сайт/приложение/соцсеть),device_type,os,geo,is_clicked (0/1)
0,1,1,38232,2025-02-01 05:54:06,app,phone,ios,Москва,0
1,1,1,58885,2025-02-01 22:30:50,site,phone,ios,Санкт-Петербург,0

In [ ]:
Installs_df = pd.read_csv(f'{data_path}/Installs.csv', sep=";")
Installs_df.head(2)

   user_id    install_timestamp source (баннер / органика / другое)
0     2908  2025-02-02 10:56:24                              banner
1    61135  2025-02-02 05:37:53                              banner

### Предобработка данных

### Сохранение данных на Google Disk

In [ ]:
new_df.to_csv(f'{data_path}/dataset_name.csv', index=False)